### ISSUE TITLE
directory tree-sitter-prebuilts not included in pip package

### ISSUE THREAD

**Issue by NicholasHoffs** [salesforce/CodeTF#11]
The pip package for salesforce-codetf==1.0.1 doesn't seem to include tree-sitter-prebuilts where the ast parser is searching for Darwin/python.so.

# Environment:

Operating System: MacOS Ventura 13.2.1 (22D68)
Python Version: 3.10.9
tree-sitter Version: 0.20.1

# Steps to Reproduce:

Perform fresh install of `salesforce-codetf=1.0.1`
Use PythonCodeUtility
Encountered an error because the .so file for Python is not included in the package

# Expected Result:
The necessary .so file for Python should be included in the my `python3.10/site-packages/codetf/tree-sitter-prebuilts/Darwin/python.so`, or there should be clear instructions on how to generate it.

# Actual Result:
The .so file for Python is missing, causing errors when attempting to parse Python code. There is no `tree-sitter-prebuilts` folder at all.

I would appreciate it if you could provide any advice on how to resolve this issue, or update the package to include the necessary files. Thank you for your time and help!

Output for running initialization of PythonCodeUtility:
OSError: dlopen(/Users/username/Projects/projname/CodeTF/codetf/tree-sitter-prebuilts/Darwin/python.so, 0x0006): tried: '/Users/username/Projects/projname/CodeTF/projname/tree-sitter-prebuilts/Darwin/python.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/username/Projects/projname/CodeTF/codetf/tree-sitter-prebuilts/Darwin/python.so' (no such file), '/Users/username/Projects/projname/CodeTF/codetf/tree-sitter-prebuilts/Darwin/python.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by bdqnghi** [comment]
The version has been pumped to 1.0.1.1 to resolve this problem, can you try again?

**Comment by NicholasHoffs** [comment]
tree-sitter issue is fixed but still having the x86, need arm64 error that's in the output above.
