### ISSUE TITLE
The example code was not working

### ISSUE THREAD

**Issue by u9wangcl** [salesforce/CodeTF#12]
![image](https://github.com/salesforce/CodeTF/assets/11343127/07517555-aa20-4a8b-a48d-f5cde8c8dcad)

**Comment by luongdolong** [comment]
I agree with the previous comment that the example code doesn't seem to be working. I tried running it myself and encountered the same issue. It would be helpful if we could get some guidance on how to fix this problem or if there's an updated version of the code available. Thank you for bringing this to our attention.

**Comment by bdqnghi** [comment]
can try you with another model?

```
from codetf.models import load_model_pipeline

code_generation_model = load_model_pipeline(model_name="codet5", task="pretrained",
            model_type="plus-770M-python", is_eval=True,
            load_in_8bit=True, load_in_4bit=False, weight_sharding=False)
            
result = code_generation_model.predict(["def print_hello_world():"])
print(result)
```

The ```plus-220M``` version of CodeT5+ may not working well.
