### ISSUE TITLE
Functionality to use a different cache directory for storing models

### ISSUE THREAD

**Issue by generative-ai758** [salesforce/CodeTF#25]
Hello, I am using your library to run inferences on the StarCoder model. I am not able to modify the cache directory as I want it to download to a different mounted disk that has more space. I tried the way of setting environment variable (TRANSFORMERS_CACHE) through Python code but it also didn't work.
Can we have a functionality to pass the cache directory path as well while loading the models using the load_model_pipeline function?

Thank You!

**Comment by bdqnghi** [comment]
hi, yes we will support that features very soon in the next release
